class Logger:
    def debug(self, message: object) -> None: ...
    def info(self, message: object) -> None: ...
    def error(self, message: object) -> None: ...
    def exception(self, message: object) -> None: ...
    def fatal(self, message: object) -> None: ...

def get_logger(
    name: str,
    *,
    level: int = ...,
    show_summary: bool = ...,
    gen_log: bool = ...,
    log_file: str | None = ...,
) -> Logger: ...
